config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/team'
  get 'static_pages/contact_us'
  get 'static_pages/diagnostic_centers'
  get 'static_pages/adoption_homes'
  get 'static_pages/surgery_centers'


  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def team
  end

  def donate
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
  def team_data
    [
      {name: 'Juan Ríos', avatar: '/assets/team/juanrios.jpeg', role: 'CEO & Founder', linkedin: 'https://www.linkedin.com/in/juan-camilo-ríos/'},
      {name: 'Laura Ríos', avatar: '/assets/team/sofia.jpg', role: 'Community manager & Co-founder', linkedin: ''},
      {name: 'Juan Garcia', avatar: '/assets/team/juandiego.jpg', role: '', linkedin: 'https://www.linkedin.com/in/juan-diego-garcia-mejia-a163b03b'},
    ]
  end
end

app/views/layouts/_footer.html.erb
<footer class="ftco-footer ftco-section img raleway_medium">
  <div class="overlay"></div>
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-2">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2 raleway_bold">Síguenos</h2>
          <div class="row">
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
              <a href="https://www.facebook.com/helpetproject"><i class="fa fa-2x fa-facebook-square" aria-hidden="true"></i></a>
              <a href="https://github.com/helpetproject/"><i class="fa fa-2x fa fa-github-square" aria-hidden="true"></i></a>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2 raleway_bold">Proyecto</h2>
          <div class="row">
            <ul class="list-unstyled">
              <li class="ftco-animate py-2 d-block"><a href="#donate">Apóyanos</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4">
         <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2 raleway_bold">Acerca de nosotros</h2>
          <ul class="list-unstyled">
            <l<li class="ftco-animate py-2 d-block"><a href="<%= static_pages_team_path%>">Equipo</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2 raleway_bold">¿Preguntas?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li class="ftco-animate py-2 d-block"><a href="#"><span class="fa fa-3x fa-mobile col-md"></span><span class="text"> +57 318 545 67 33</span></a></li>
              <li class="ftco-animate py-2 d-block"><a href="#"><span class="fa fa-2x fa-envelope-o col-md"></span><span class="text">contacto@helpetproject.info</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          HelpetProject es un proyecto en desarrollo bajo la licencia GPLv3. El diseño de este template se basa en <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_metas.html.erb
<meta name="description" content="HelPet Project - «Quien alimenta a un animal hambriento, alimenta su propia alma» Charles Chaplin" />
<meta name="keywords" content="helpet project, helpet, help, pet, adoptar, dar en adopcion, apóyanos" />
<meta name="Language" content="Español"/>
<meta name="email" content="contacto@helpetproject.info"/>
<meta name="revisit-after" content="1 days"/>
<meta name="expires" content="never"/>
<meta name="author" content="HelPet Project"/>
<meta name="geo.region" content="CO-ANT">
<meta name="geo.placename" content="Medellín">
<meta name="robots" content="index,follow" />
<meta property="og:title" content="helpet project" />
<meta property="og:url" content="http://www.helpetproject.info" />
<meta property="og:site_name" content="HelpetProject" />
<meta name="google" content="notranslate" />

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-white ftco_navbar bg-white ftco-navbar-light scrolled awake raleway_bold navbar-size" id="ftco-navbar">
  <div class="container">
    <div class="navbar-brand hidden-xsnavbar-brand mx-auto">
      <ul class="navbar-nav logo_media">
        <li class="nav-item">
          <a class="white-circle">
            <img class="logo img-circle" src="/assets/helpet_logo.png" alt="Logo">
          </a>
        </li>
      </ul>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        ☰
    </button>
    <div class="navbar-collapse collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Inicio', root_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <a class="nav-link slide" href="#pets">Adopta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link slide" href="#give_in_adoption">Dar en adopción</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link slide" href="#download-app">Descarga la APP</a>
        </li>
        <li class="nav-item">
          <a class="nav-link slide" href="#donate">Apóyanos</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelPet Project | Adopta una mascota | Dar en adopción una mascota</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render '/layouts/metas' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <%= yield %>
    <%= render '/layouts/footer' %>
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/static_pages/_adopt.html.erb
<section class="ftco-section" id="pets">
  <div class="container-fluid">
    <div class="container">
      <div class="row col-lg-12">
        <div class="col-lg-6" id="bg4">
        </div>
        <div class="col-lg-6">
            <div class="row justify-content-center pb-3">
              <div class="col-md-5 col-lg-10 ftco-animate text-center">
                <h2 class="raleway_bold"><span class="span_titles">¿Por qué Adoptar?</span></h2>
              </div>
            </div>
          <p class="raleway_light text-justify">
            Salva una vida: Muchas personas abandonan a sus mascotas en la calle mientras que otras las entregan en albergues o refugios. Debido al poco espacio en estos lugares, en muchos casos los animales son sacrificados. Los que terminan en la calle pueden morir de hambre, atropellados, abusados o enfermos.
          </p>
          <p class="raleway_light text-justify"> 
            Te brindan amor incondicional: Pase lo que pase, la mascota siempre estará disponible y será la primera que se alegre cuando llegue a casa. El amor que brindan los animales es el más puro.
          </p>
          <p class="raleway_light text-justify"> 
            Las mascotas que se encuentran en tiendas, por lo general, viven dentro de jaulas y lejos del calor humano. Además, se suele desconocer su origen y si fueron criadas responsablemente. Al comprar, se continúa con el ciclo de venta y encierro.
          </p>
          <p class="raleway_light text-justify"> 
            Compañía: Tener una mascota hará que nunca se sienta solo. Son fieles compañeros.
          </p>
          <p class="raleway_light text-justify"> 
            Te mantienen activo: Pasar tiempo paseando al perro o jugando con el gato es una buena manera de hacer ejercicio, de fortalecer el vínculo con la mascota y, además, en el caso de los perros, lo expone a socializar con otras personas.
          </p>
          <p class="raleway_light text-justify"> 
            Se le da oportunidad a otros: Al adoptar, no solo ilumina la vida de un animal, además ayuda a liberar espacio en un albergue, lo que permite rescatar a más animales abandonados a su suerte.
          </p>
          <p>Fuente: <a href="https://elclubmascotas.com/blog/la-importancia-de-adoptar">El club mascotas</a></p>
        </div>
       
      </div>
      
      <div class="row col-lg-12 mt-5" id="give_in_adoption">
        <div class="col-lg-6">
          <div class="row justify-content-center pb-3">
            <div class="col-md-5 col-lg-10 ftco-animate text-center">
              <h2 class="raleway_bold"><span class="span_titles">¿Por qué dar en Adopción?</span></h2>
            </div>
          </div>
          <p class="raleway_light text-justify">
            Antes de abandonar a tu mascota debes pensar en que un perro es más que un amigo incondicional, como un miembro más de la familia. Y es que te complementa en los momentos más felices y está a tu lado en los más tristes. Por supuesto, debes tener en cuenta que los canes también sufren y tienen sentimientos. Eso sí, nunca te guardan rencor, no te juzgan y siempre te quieren. Por otro lado, los perros ayudan a hacer ejercicio y a hacer amigos, además de ser los complementos perfectos para niños y mayores. Tampoco hay que olvidar que abandonar a un animal puede provocar terribles consecuencias, tanto para él como para la gente, ya que pueden suceder accidentes.
          </p>
          <p>Fuente: <a href="https://animalmascota.com/razones-para-no-abandonar-a-un-perro/">Animal mascota</a></p>
          
          <p class="raleway_light text-justify"> 
            Cada individuo por el solo hecho de existir se hace merecedor de gozar de estas libertades y más aún por pertenecer a la población de fauna doméstica. Somos los seres humanos quienes nos compete garantizar que así sea. Que estas libertades sean brindadas a cada individuo, es la obligación que contrajo nuestra especie en el pasado cuando consumó la acción de domesticar un segmento de fauna como animales de compañía.
          </p>
          <p>Fuente: <a href="https://comunidadmilhuellitas.org/">Comunidad mil huellitas</a></p>

        </div>
        <div class="col-lg-6" id="bg5">

          </div>
      </div>


    </div>
  </div>
</section>

app/views/static_pages/_cards_centers.html.erb
<section class="ftco-counter ftco-intro raleway_light" id="cards_centers">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-4 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 color-1 align-items-stretch">
          <div class="text">
            <div class="col-md">
              <i class="fa fa-hospital-o fa-5x" aria-hidden="true" id="fontawesome_hospital"></i>
            </div>
            <div class="col-md-12">
              <p class="cards-centers"><%= link_to 'Centros de Diagnóstico', static_pages_diagnostic_centers_path, class: 'blue-text' %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 color-2 align-items-stretch">
          <div class="text">
            <div class="col-md">
              <i class="fa fa-paw fa-5x" aria-hidden="true"  id="fontawesome_paw_medkit"></i>
            </div>
            <div class="col-md-12">
              <p class="cards-centers"><%= link_to 'Hogares de Adopción', static_pages_adoption_homes_path, class: 'white-text' %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 color-3 align-items-stretch">
          <div class="text">
            <div class="col-md">
              <i class="fa fa-medkit fa-5x" aria-hidden="true" id="fontawesome_paw_medkit"></i>
            </div>
            <div class="col-md-12">
              <p class="cards-centers"><%= link_to 'Centros de Cirugía', static_pages_surgery_centers_path, class: 'white-text' %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_contact.html.erb
<section class="ftco-section-3 img" id="contact">
  <div class="container">
    <div class="row d-md-flex">
      <div class="col-md-6 volunteer pl-md-5 ftco-animate">
        <h3 class="mb-3 raleway_bold">Envianos tu mensaje</h3>
        <form action="#" class="volunter-form">
          <div class="form-row d-flex ftco-animate">
            <div class="col-6 form-group">
              <input type="text" class="form-control" placeholder="Nombre">
            </div>
            <div class="col-6 form-group">
              <input type="email" class="form-control" placeholder="Email">
            </div>
          </div>
          <div class="form-row d-flex ftco-animate">
            <div class="col-6 form-group">
              <input type="text" class="form-control" placeholder="Número Celular">
            </div>
            <div class="col-6 form-group">
              <input type="email" class="form-control" placeholder="Asunto">
            </div>
          </div>
          <div class="form-row d-flex ftco-animate">
            <div class="form-group col-12">
              <textarea name="" id="" cols="30" rows="3" class="form-control" placeholder="Mensaje"></textarea>
            </div>
            <div class="form-group">
              <input type="submit" value="Enviar mensaje" class="btn btn-info py-3 px-5 raleway_light">
            </div>
          </div>
        </form>
      </div>

      <div class="col-md-6 volunteer pl-md-5 ftco-animate">
        <div class="row">
          <h3 class="mb-3 raleway_bold">Hola!</h3>
        </div>
        <div class="row raleway_medium color-3">
          <p class="p_contact color-3">Tu mensaje es muy importante para nosotros. Responderemos a la menor brevedad posible.</p>
        </div>
        <div class="row">
          <h3 class="mb-3 raleway_bold">Contacto</h3>
        </div>
        <div class="row raleway_light color-3">
          <i class="fa fa-envelope fa-2x" aria-hidden="true"></i><p class="p_contact mx-2">E-mail: contacto@helpetproject.info</p>
        </div>
        <div class="row raleway_light color-3">
          <i class="fa fa-phone fa-2x" aria-hidden="true"></i><p class="p_contact mx-2">Teléfono: (+57) 318 545 6733</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_donate.html.erb
<section class="ftco-section donate-section" id="donate">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-5 col-lg-12 ftco-animate text-center">
        <h2 class="raleway_bold h2_titles"><span class="span_titles">Apóyanos</span></h2>
      </div>
    </div>

    <div class="row d-md-flex mt-5">
      <div class="col-lg-5 pl-md-5 ftco-animate" id="bg3"> </div>

      <div class="col-lg-7 volunteer pl-md-5 ftco-animate">
        <div class="row raleway_medium color-3">
          <p class="raleway_light text-justify">
            Con tu donación no solo ayudarás a cubrir los costos de arrendamiento de la infraestructura necesaria para que HelPet siempre esté al alcance de la comunidad, también contribuirás a que siempre esté en constante desarrollo.
          </p>
          <p class="raleway_light text-justify">
            Si deseas donar a través de PayPal haz clic en el botón hacer una donación, o si deseas hacerla por medio de una consignación o transferencia bancaria puedes comunicarte directamente con nosotros haciendo clic en el botón de Whatsapp que aparece en pantalla.<br>
          </p>
          <p class="raleway_light text-justify">
            Gracias por tu apoyo.              
          </p>
        </div>
        <%= link_to 'Hacer una donación', 'https://www.paypal.me/helpetproject', class: 'btn btn-info btn-outline-white px-5 py-3'%>
        <div class="row mt-5">
          <h3 class="mb-3 raleway_bold">Contacto</h3>
        </div>
        <div class="row raleway_light color-3">
          <i class="fa fa-envelope fa-2x" aria-hidden="true"></i><p class="p_contact mx-2">E-mail: contacto@helpetproject.info</p>
        </div>
        <div class="row raleway_light color-3">
          <i class="fa fa-phone fa-2x" aria-hidden="true"></i><p class="p_contact mx-2">Teléfono: (+57) 318 545 6733</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_download_app.html.erb
<section class="ftco-section4 bg-blue" id="download-app">
  <div class="container">
    <div class="row d-flex mb-5 contact-info">
      <div class="col-md-6">
        <p class="white-text raleway_bold download-app-text">Descarga la APP</p>
      </div>
      <div class="col-md-3">
      <p data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><a href="" class="btn btn-info btn-outline-white px-5 py-3 mt-3">Play Store</a></p>
      </div>
      <div class="col-md-3">
      <p data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><a href="" class="btn btn-info btn-outline-white px-5 py-3 mt-3">APP Store</a></p>
      </div>
    </div>
  </div>
</section>
<div class="col-lg-12" id="bg-download-app"></div>

app/views/static_pages/_events.html.erb
<section class="ftco-section" id="events">
  <div class="container-fluid">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-5 col-lg-10 ftco-animate text-center">
        <h2 class="raleway_bold h2_titles"><span class="span_titles">Eventos</span></h2>
      </div>
    </div>
    <div class="container">
        <div class="row">
           <div class="col-md-12">
              <ul class="timeline">
                 <li class="timeline wow bounceInUp">
                    <div class="timeline-badge warning"><i class="fa fa-clock-o"></i></div>
                    <div class="date-info">
                       <span class="day">29</span><span class="month"> Jan</span><span class="year"> 2017</span>
                    </div>
                    <div class="timeline-panel">
                       <div class="timeline-heading">
                          <h6 class="timeline-title">Evento de prueba</h6>
                       </div>
                       <div class="timeline-body">
                          <p>
                             Release highlights :
                             Layout changed inline with other Cartwheel applications. (Menu based and full-screen).
                             Introduced filters and sorting of Actions items.
                             Print facility to support printing of any saved reports (including previous reports)
                          </p>
                       </div>
                    </div>
                 </li>
                 <li class="timeline-inverted wow bounceInUp">
                    <div class="timeline-badge danger"><i class="fa fa-clock-o"></i></div>
                    <div class="date-info">
                       <span class="day">04</span><span class="month"> Feb</span><span class="year"> 2017</span>
                    </div>
                    <div class="timeline-panel">
                       <div class="timeline-heading">
                          <h6 class="timeline-title">Evento de prueba</h6>
                       </div>
                       <div class="timeline-body">
                          <p>
                             Release highlights :
                             Layout changed inline with other Cartwheel applications. (Menu based and full-screen).
                             Introduced filters and sorting of Actions items.
                             Print facility to support printing of any saved reports (including previous reports)
                          </p>
                       </div>
                    </div>
                 </li>
                 <li class="timeline-inverted wow bounceInUp">
                    <div class="timeline-badge danger"><i class="fa fa-clock-o"></i></div>
                    <div class="date-info">
                       <span class="day">31</span><span class="month"> Enero</span><span class="year"> 2018</span>
                    </div>
                    <div class="timeline-panel">
                       <div class="timeline-heading">
                          <h6 class="timeline-title">Evento de prueba</h6>
                       </div>
                       <div class="timeline-body">
                          <p>
                             Release highlights :
                             Layout changed inline with other Cartwheel applications. (Menu based and full-screen).
                             Introduced filters and sorting of Actions items.
                             Print facility to support printing of any saved reports (including previous reports)
                          </p>
                       </div>
                    </div>
                 </li>
                 <li class="timeline-inverted wow bounceInUp">
                    <div class="timeline-badge danger"><i class="fa fa-clock-o"></i></div>
                    <div class="date-info">
                       <span class="day">25</span><span class="month"> Jan</span><span class="year"> 2018</span>
                    </div>
                    <div class="timeline-panel">
                       <div class="timeline-heading">
                          <h6 class="timeline-title">Evento de prueba</h6>
                       </div>
                       <div class="timeline-body">
                          <p>
                             Release highlights :
                             Layout changed inline with other Cartwheel applications. (Menu based and full-screen).
                             Introduced filters and sorting of Actions items.
                             Print facility to support printing of any saved reports (including previous reports)
                          </p>
                       </div>
                    </div>
                 </li>
              </ul>
           </div>
        </div>
     </div>
   </section>

app/views/static_pages/_happy_endings.html.erb
<section class="ftco-section bg-happy_endings" id= "happy_endings">
  <div class="container-fluid">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-5 col-lg-10 ftco-animate text-center">
        <h2 class="raleway_bold happy_endings_bar h2_titles"><span class="span_titles happy_endings_tile">Finales Felices</span></h2>
      </div>
    </div>
    <div class="container">
      <section class="ftco-gallery">
        <div class="d-md-flex">
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
        </div>
        <div class="d-md-flex">
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
          <a href="/assets/happy_endings.png" class="gallery image-popup d-flex justify-content-center align-items-center img ftco-animate margin_pets" style="background-image: url(/assets/happy_endings.png);">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="icon-search"></span>
            </div>
          </a>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/static_pages/_sponsors.html.erb
<section class="customer-logos slider">
  <div class="container">
    <div class="row blog">
        <div class="col-md-12">
            <div id="blogCarousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#blogCarousel" data-slide-to="0" class="active"></li>
                  <li data-target="#blogCarousel" data-slide-to="1"></li>
                </ol>

                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="row">
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                        </div>
                        <!--.row-->
                    </div>
                    <!--.item-->

                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                            <div class="col-md-2 col-6">
                                <a href="#">
                                    <img src="/assets/helpet_logo.png" alt="Image" style="max-width:100%;">
                                </a>
                            </div>
                        </div>
                        <!--.row-->
                    </div>
                    <!--.item-->

                </div>
                <!--.carousel-inner-->
            </div>
            <!--.Carousel-->

        </div>
    </div>
  </div>
</section>

app/views/static_pages/index.html.erb
<div class="hero-wrap" style="background-image: url('/assets/bg_7.jpg');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
    <div class="row no-gutters slider-text align-items-center" data-scrollax-parent="true">
        <div class="col-md-5 ftco-animate text-center welcome_text" data-scrollax=" properties: { translateY: '70%' }">
          <h1 class="mb-4" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Bienvenido a</h1>
          <p class="mb-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><%= image_tag 'helpet.png', height: 80, width: 200 %></p>
          <p data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><a href="#donate" class="btn btn-info btn-outline-white px-5 py-3">Apóyanos</a></p>
      </div>
    </div>
</div>

<%= render 'adopt' %>
<%= render 'download_app' %>
<%= render 'donate' %>

<a href="https://<%= browser.device.mobile? ? 'api' : 'web'%>.whatsapp.com/send?phone=573185456733&amp;text=Hola HelPet Project." class="whatsapp" target="_blank"><i class="fa fa-whatsapp whatsapp-float"></i></a>